import { SessionProvider } from "next-auth/react"
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        rel: "icon",
        type: "image/png",
        url: "/images/logo.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${roboto.className} antialiased`}
      >
        <SessionProvider>
          {children}
        </SessionProvider>
        <Toaster
            richColors
            position="top-center"
            toastOptions={{
              classNames: {
                title: '!font-semibold',
              },
            }}
          />
      </body>
    </html>
  );
}
